# The first line of code signifies the creation of a YAML file.
---
deployment:
  tasks:
  # The line below defines a DEPLOYPATH with a path to the document root of my website (public_html). I'll be able to use this in subsequent commands.
    - export DEPLOYPATH=/home/carorode/public_html/
  # These subsequent Bash commands copy ('cp') various files and folders to my website's document root as defined above.
  # The first two commands copy the 'html' and 'css' directories to the document root.  '-R' copies the contents of a directory.
    - /bin/cp -R html $DEPLOYPATH
    - /bin/cp -R projects $DEPLOYPATH
  # These next commands copy indiviual files from the Git root to the document root.
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp directory.md $DEPLOYPATH
