# The first line of code signifies the creation of a YAML file.
---
deployment:
  tasks:
  # The line below defines a DEPLOYPATH with a path to the document root of my website (public_html). I'll be able to use this in subsequent commands.
    - export DEPLOYPATH=/home/carorode/public_html/
  # Subsequent Bash commands copy ('cp') various files and folders to my website's document root as defined above.
  # These next commands copy individual files from the Git root to the document root.
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
  # This command copies a directory and its contents from the Git root to the document root 
    - /bin/cp -R projects $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R prana $DEPLOYPATH
    - /bin/cp -R todo-today $DEPLOYPATH
    - /bin/cp -R music-box $DEPLOYPATH
    - /bin/cp -R vss $DEPLOYPATH