---
deployment:
  tasks:
  # The line below defines a DEPLOYPATH with a path to the document root of my website. I'll be able to use this in subsequent commands.
    - export DEPLOYPATH=/home/carorode/public_html/
  # These subsequent commands copy ('cp') various files and folder to my website's document root as defined above.
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp directory.md $DEPLOYPATH
