# The first line of code signifies the creation of a YAML file.
---
deployment:
  tasks:
  # The line below defines a DEPLOYPATH with a path to the document root of my website. I'll be able to use this in subsequent commands.
    - export DEPLOYPATH=/home/carorode/public_html/
  # These subsequent Bash commands copy ('cp') various files and folder to my website's document root as defined above.
  # Lines 9-11 are files to be copied while Line 12 is the directory.  '-R' copies the contents of a directory.
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp directory.md $DEPLOYPATH
    - /bin/cp -R html $DEPLOYPATH
